encoding_class: KmerFreqRepertoireEncoder
encoding_file: encoder.pickle
encoding_name: feature_size_4
encoding_parameters:
  k: 4
  k_left: 1
  k_right: 1
  max_gap: 0
  min_gap: 0
  name: feature_size_4
  normalization_type: l2
  reads: unique
  scale_to_unit_variance: true
  scale_to_zero_mean: true
  sequence_encoding: continuous_kmer
labels_with_values:
  signal_cancer:
  - false
  - true
ml_method: LogisticRegression
ml_method_name: logistic_regression
preprocessing_file: preprocessing_sequence.pickle
preprocessing_parameters: {}
preprocessing_sequence_name: null
software_used: scikit-learn 0.24.2
train_dataset_id: d329efe6-e617-11eb-a588-0242ac110002
train_dataset_name: d329efe6-e617-11eb-a588-0242ac110002
